### ISSUE TITLE
Additional fields when parsing primary.xml

### ISSUE THREAD

**Issue by thutterer** [ikapelyukhin/repomd-parser#8]
Hallo @ikapelyukhin :wave: 

I started looking into this gem and maybe using it for SCC. Looks super promising, but I just noticed that parsing a primary doesn't return all the fields we'd need, like summary, description, license.

Can we have these? Anything planned here already? I can do a draft PR, just wanted to ask your opinion. Should I just add parsing these fields always, or attempt something like optional "extra_fields"?

Thanks!

**Comment by ikapelyukhin** [comment]
Hey, 2D. :wave: 

> Anything planned here already?

Nothing planned, because those other fields aren't used anywhere else (e.g. RMT or [repo-tools](https://github.com/ikapelyukhin/repo-tools)).

> Can we have these?

Sure, especially if you add them yourself :slightly_smiling_face: 

> I can do a draft PR, just wanted to ask your opinion. Should I just add parsing these fields always, or attempt something like optional "extra_fields"?

Something optional could be nice (maybe supplying an optional code block that does additional parsing -- the actual values are sometimes an XML element attribute and sometimes element's `text()`), but the list of fields is hardcoded into `RepomdParser::Reference` class definition, having those defined dynamically kind of defies the purpose of having that class at all. Besides, the set of possible fields is very limited (it's not like you can add a random XML property to SUSE repos).

So right now I'm gravitating towards just adding those fields, it is the way of least resistance. :slightly_smiling_face: I'd recommend testing with RES repos and making sure nothing breaks, though -- RedHat repos have a slightly different XML format.
